# REPLACE WITH PATHS TO SUPPORT DATA OR 
# IMPORT FROM HIGHER LEVEL CONFIG REPO
opds_path = ""
coat_path = ""
cam_path = ""

[spectrum] #---------------------------------------------------------------------
# PLACEHOLDER: This will be replaced with a filter specification
wvl_reference = '625e-9m' # central wavelength of baselined sloan R-band filter  
bandwidth = 0.24 # bandwidth of baselined sloan R-band filter; fraction of wvl_reference

[sources] #---------------------------------------------------------------------

[sources.guide_star_1]
magnitude = 17 # R-band Rmag
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sources.guide_star_2]
magnitude = 17 # R-band Rmag
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sources.guide_star_3]
magnitude = 17 # R-band Rmag
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sources.guide_star_4]
magnitude = 17 # R-band Rmag
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sources.guide_star_5]
magnitude = 17 # R-band Rmag
spectral_profile = "pickles_uk_23.fits" # host star spectral template (default is Pickles G0)

[sensor] #---------------------------------------------------------------------

exposure_time = 1                   # seconds
black_level = 100
gain = 100
pixel_size = '3.76e-6m'
qe = "ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_QE_curve.fits" 
dark_current = "ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Dark_Current_vs_Sensor_Temperature.csv"
gain_curve = "ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Gain_vs_Gain_Setting.csv"
read_noise = "ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Read_Noise_vs_Gain_Setting.csv"
well_depth = "ZWO_ASI6200MM/ZWO_ASI6200MM_Pro_Well_Depth_vs_Gain_Setting.csv"
temp_nominal = '20Celsius' # CBE
temp_nominal_range = '1Kelvin' # CBE
temp_stability = '0.1Kelvin/hour' # WAG
